### ISSUE TITLE
feat(function): useQuerySelector and useQuerySelectorAll

### ISSUE THREAD

**Issue by hairyf** [uni-helper/uni-use#17]
### 对问题的清晰和简明的描述

- useQuerySelector
- useQuerySelectorAll

### 推荐的解决方案

基础实现（useQuerySelector）：

```ts
type QuerySelectorMode = 'boundingClientRect' | 'context' | 'fields' | 'node' | 'scrollOffset'

function useQuerySelector(mode: QuerySelectorMode, fields?: ...) {
  const { all = false, fields = {} } = options
  // create manual promise
  const ready = createDeferred()
  // current component instance
  const instance = getCurrentInstance()

  async function query(selector: string) {
    return new Promise((resolve) => {
      ready.then(() => {
        const selectQuery = uni.createSelectorQuery()
        //...
      })
    })
  }

  onMounted(ready.resolve)

  return query
}

function useQuerySelectorAll() {
  // ...
}
```

```ts
// setup
const querySelectorRect = useQuerySelector('boundingClientRect')
const querySelectorRectAll = useQuerySelectorAll('boundingClientRect')
const querySelectorFields = useQuerySelector('fields', {  size: true, ... })

async function getRect() {
  const rect = await querySelectorRect('#id')
}
async function getFields() {
  const rect = await querySelectorFields('#fields-id', { /* overrides options */ })
}
```

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by ModyQyW** [comment]
后悔了，怎么没有“我愿意提交一个 PR”可供你勾选

**Comment by ModyQyW** [comment]
翻了下记录发现在 0.12.0 移除了 selectorQuery 相关的方法，因为我认为它是一个无状态逻辑方法。能举出一个反例说服我加回来吗？🤔️

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/31850793/236435980-91e711cb-7498-43d2-a89f-0e66ba55e74d.png">

**Comment by hairyf** [comment]
嗨！我没有看到任何相关 selectorQuery 的记录，另外 `useSelectorQuery` 实际上是有状态的，（`onMounted` 与 `getCurrentInstance`）

实际上，我并不喜欢讨论这类所谓的组合式理论，这完全是经验所得，例如 [vueuse#useDebounceFn](https://vueuse.org/shared/useDebounceFn/), [vueuse#useThrottleFn](https://vueuse.org/shared/useThrottleFn/)

另外，`useSelectorQuery` 能避免在不同的组件上定义大量重复的链式调用，你可以查看 [ano-ui#a-collapse-transition](https://github.com/ano-ui/ano-ui/blob/main/packages/ano-ui/src/components/ACollapseTransition/use-a-collapse-transition.ts#LL14C5-L14C5) 的实现，这很棒！

我很乐意提供一个 PR（这没什么困难的）不过我现在正在忙于 vue3-pixi-renderer 的开发，可能会晚一些。

> 如果这不能说服你，请关闭这个问题（没关系，我不介意 ❤️

**Comment by hairyf** [comment]
我看到了 v0.11.0 版本前的 `useSelectorQuery` 实现，简单来说它并没有减轻应用复杂度，这不是我想要的

**Comment by ModyQyW** [comment]
> 我看到了 v0.11.0 版本前的 `useSelectorQuery` 实现，简单来说它并没有减轻应用复杂度，这不是我想要的

确实，它的作用微乎其微。

> 我很乐意提供一个 PR（这没什么困难的）

非常欢迎！如果你没有空的话也可以等待我增加这个方法。
