### ISSUE TITLE
使用@uni-helper/uni-use报错

### ISSUE THREAD

**Issue by yuanjinkunlou** [uni-helper/uni-use#18]
### 描述问题

我在使用@uni-helper/uni-use的时候抛出了一个错误：
"TransitionGroup" is not exported by "node_modules/vue-demi/lib/index.mjs", imported by "node_modules/@vueuse/core/index.mjs".
at ../node_modules/@vueuse/core/index.mjs:3:0
  1: import { noop, makeDestructurable, toValue, isClient, tryOnScopeDispose, isIOS, tryOnMounted, computedWithControl, is... 
  2: export * from '@vueuse/shared';
  3: import { isRef, ref, shallowRef, watchEffect, computed, inject, isVue3, version, defineComponent, h, TransitionGroup,... 
     ^
  4: 
  5: function computedAsync(evaluationCallback, initialState, optionsOrRef) {
这会不会是vueuse版本太高和uni-app冲突了？

### 复现

![image](https://github.com/uni-helper/uni-use/assets/126596599/7fabc36f-b23f-4919-af2a-a748d8918667)

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz    
    Memory: 19.25 GB / 31.83 GB
  Binaries:
    Node: 16.19.1 - ~\AppData\Local\pnpm\node.EXE
    npm: 8.19.3 - ~\AppData\Local\pnpm\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.50)
    Internet Explorer: 11.0.19041.1566
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
请问你项目里安装了 @vueuse/core@10 吗？

**Comment by yuanjinkunlou** [comment]
没有

**Comment by yuanjinkunlou** [comment]
可以了，我把@vueuse/core降到9.13.0就好了

**Comment by ModyQyW** [comment]
uni-use 本身是用 @vueuse/core^9.13.0 的，可能是其它库使用到了 @vueuse/core@10 导致了这个问题出现。后续我们会更新一下 README。
