### ISSUE TITLE
BUG: `useStorageAsync` didn't handle data-not-found exception and write default value

### ISSUE THREAD

**Issue by MaikoTan** [uni-helper/uni-use#25]
### Describe the bug

Unlike the `useStorageAsync` function in `VueUse`, instead, an exception would be thrown and the default value was not written into the storage in UniApp if the data didn't present initially.

![image](https://github.com/uni-helper/uni-use/assets/19927330/689cdc57-2e04-4e94-885c-44fd3d30b605)

https://github.com/uni-helper/uni-use/blob/974e6063713a640d33f7c5ad2c0d64a9e9d7775c/src/useStorageAsync/index.ts#L215-L241

I think it is because the line 217 throws the exception mentioned above rather than return a `null` value which leads the next line `rawValue == null` comparation makes no sense.

### Reproduction

```ts
import { useStorageAsync } from '@uni-helper/uni-use'

const test = useStorageAsync('test', 'default-value') // throws exception
console.log(test.value)
```

### System Info

```Shell
System:
    OS: Linux 6.4 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
    Memory: 3.59 GB / 11.51 GB
    Container: Yes
    Shell: 3.6.1 - /usr/bin/fish
  Binaries:
    Node: 20.5.0 - /tmp/xfs-582e2a7f/node
    Yarn: 3.4.1 - /tmp/xfs-582e2a7f/yarn
    npm: 9.8.1 - /usr/bin/npm
    pnpm: 8.6.12 - /usr/bin/pnpm
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ModyQyW** [comment]
Thanks a lot! Should be fixed in 0.14.1.
