### ISSUE TITLE
useStorageAsync 会无限触发 watch，导致cpu占用过高，页面卡死

### ISSUE THREAD

**Issue by romejiang** [uni-helper/uni-use#28]
### 描述问题

useStorageAsync 会无限触发 watch，导致cpu占用过高，页面卡死

**_设置 {listenToStorageChanges: false} 后这个情况会消失，所以可能和这部分逻辑有关系。_**

<img width="1299" alt="image" src="https://github.com/uni-helper/uni-use/assets/1053325/f9d3591c-f84d-495a-bae1-b0eca9fecfdb">

### 复现

git clone https://github.com/uni-helper/uni-use.git
cd  uni-use
pnpm i
pnpm build
cd playground
修改 package.json 
"@uni-helper/uni-use": "workspace:*", to "@uni-helper/uni-use": "file:../dist",
pnpm dev:h5

编辑页面 index.vue

```vue
import { useStorageAsync } from '@uni-helper/uni-use'
const state = useStorageAsync('my-store', { hello: 'hi', greeting: 'Hello' })
watchEffect(() => {
  console.log('clipboardData', state.value);
});
const updateStorage = async () => {
  state.value.hello = Math.random().toFixed(2).toString();
}


<template>
  <view class="content">
    {{ state.hello }}
    <button @click="updateStorage">Update Clipboard Data</button>
  </view>
</template>
```

### 系统信息

```Shell
System:
    OS: macOS 14.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 272.08 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.7.5 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 17.1
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
这个星期有点忙，我最快下周看这个问题，如果愿意 PR 欢迎提交，谢谢理解 🙏

**Comment by ModyQyW** [comment]
请试试 0.17.0 🙏

**Comment by romejiang** [comment]
> 请试试 0.17.0 🙏

感谢更新，试了一下

发现 watchWithFilter 方法的 callback 参数 value, oldValue 总是一样的，导致一直返回true，而无法更新 storage。

```ts
  const serialized = await serializer.write(value);
  const oldSerialized =  await serializer.write(oldValue);
  //   这里value 和 oldValue 总是一样
  if (serialized === oldSerialized) return;
```

改成这样可以正常使用。

```ts
  const serialized = await serializer.write(value);
  const oldSerialized = await storage!.getItem(key)
```

**Comment by ModyQyW** [comment]
> 发现 watchWithFilter 方法的 callback 参数 value, oldValue 总是一样的，导致一直返回true，而无法更新 storage。

方便告诉我你测试时使用的样例是什么吗？

**Comment by romejiang** [comment]
复现流程

```shell
git clone https://github.com/uni-helper/uni-use.git
cd uni-use 
pnpm i  
pnpm build  
cd playground 
pnpm dev:h5
```

然后编辑  ./playground/src/pages/index/index.vue

```vue
<script setup lang="ts">
import { ref, watchEffect } from 'vue';
import { useStorageAsync } from '@uni-helper/uni-use'

const title = ref('Hello');

const state = useStorageAsync('my-store', { hello: 'hi', greeting: 'Hello' })
watchEffect(() => {
  console.log('clipboardData', state.value);
});
const updateStorage = async () => {
  state.value.hello = Math.random().toFixed(2).toString();
}

</script>

<template>
  <view class="content">
    <image class="logo" src="/static/logo.png" />
    <view class="text-area">
      <text class="title">{{ title }}</text>
    </view>
    {{ state.hello }}
    <button @click="updateStorage">Update Clipboard Data</button>
  </view>
</template>

<style>
.content {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.logo {
  height: 200rpx;
  width: 200rpx;
  margin-top: 200rpx;
  margin-left: auto;
  margin-right: auto;
  margin-bottom: 50rpx;
}

.text-area {
  display: flex;
  justify-content: center;
}

.title {
  font-size: 36rpx;
  color: #8f8f94;
}
</style>

```

**Comment by ModyQyW** [comment]
我这里使用的是这个例子，点击按钮可以正常更新 hello 的值而且也没有死循环。可以给我分享一下无法更新 storage 详细的复现步骤吗？

**Comment by romejiang** [comment]
0.17.0 更新后，无限循环的问题解决了。但因为前面提到的原因，更新后 localStorage 中的值不会被保存。测试方式参考下图：

![1699924555079](https://github.com/uni-helper/uni-use/assets/1053325/e84b637c-edc4-418b-a1bc-63a8bfa3db8f)


这是我的源码，复现方式和前面提到的一样：

[uni-use.tar.gz](https://github.com/uni-helper/uni-use/files/13343464/uni-use.tar.gz)

**Comment by ModyQyW** [comment]
哦我明白了，我这边再看看，感谢你指出的问题

**Comment by romejiang** [comment]
> 请试试 0.17.1 🙏

🎉 解决了，感谢！！！
