### ISSUE TITLE
没有导出 usePageScroll 方法

### ISSUE THREAD

**Issue by sunpm** [uni-helper/uni-use#40]
### 描述问题

![13b60f459045358ad3b99b57ab36ca7f](https://github.com/uni-helper/uni-use/assets/35005831/4497aea1-a12d-46fa-ac5c-7aee21fc5c81)
![29749f0ce14f0efa95eac556ce4d6e04](https://github.com/uni-helper/uni-use/assets/35005831/8d48eaf4-c2ae-4721-b236-3fa3397f0bd5)
![8f6a438d7edd04549732aacc8f3bbd6c](https://github.com/uni-helper/uni-use/assets/35005831/f2bb511e-c163-4b1d-945e-34955263aaaf)

### 复现

https://github.com/sunpm/vitesse-uniapp-vue3/blob/uni-use-issue/src/pages/index/index.vue

### 系统信息

System:
    OS: macOS 12.6.5
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 31.03 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
  Browsers:
    Chrome: 124.0.6367.208
    Firefox: 63.0.3
  npmPackages:
    @vueuse/core: 9
    @uni-helper/uni-use: ^0.19.10
    vue: ^3.4.21

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by edwinhuish** [comment]
fixed 885454705164557f1e19633fa3ef237bc64ef673
