### ISSUE TITLE
useRouter 的 navigate 跳转的 path 使用变量集合储存

### ISSUE THREAD

**Issue by sunpm** [uni-helper/uni-use#47]
### 对问题的清晰和简明的描述

由于 uniapp 的路由是写写在 pages.json 中，无法动态改变。
useRouter 的 navigate 在尝试 uni.switchTab 之后发现不是 tab，再使用 uni.navigateTo 进行跳转。
每次跳转都会重复该前置处理，是否耗费性能？

### 推荐的解决方案

尝试 uni.switchTab 进入错误拦截后可以将这个 path 保存在一个变量集合中，下次还是这个 path，不需要再使用 uni.switchTab 前置跳转

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读 [贡献指南](https://github.com/antfu/contribute) 和 [一位疲惫的维护者的笔记](https://github.com/ModyQyW/tired-maintainer)。
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by edwinhuish** [comment]
有考虑过，但是由于错误拦截的错误不确定是否 tab 页导致的，故未做相应修改。也考虑过读取 pages.json，但考虑到有 uni-pages 这种动态生成的pages.json，也就需要每次跳转读取一次 pages.json 来确保跳转正确。

鉴于上面2个原因，在写的时候未做细分测试，故未优化。

**Comment by sunpm** [comment]
关于第一个原因，useRouter 也未对错误进行解析就使用 uni.navigateTo 尝试跳转
https://github.com/uni-helper/uni-use/blob/359b0fef698b59bf25ca448a46ef0e5e25409822/src/useRouter/index.ts#L128

tabbar 配置可以通过参数传入，这里是否可以再判断多一个在 uni.switchTab 中的错误 path 呢
https://github.com/uni-helper/uni-use/blob/359b0fef698b59bf25ca448a46ef0e5e25409822/src/useRouter/index.ts#L142-L146

**Comment by edwinhuish** [comment]
如群内沟通，此代码已 catch 了 tabbar 跳转错误。

https://github.com/uni-helper/uni-use/blob/359b0fef698b59bf25ca448a46ef0e5e25409822/src/useRouter/index.ts#L128

如果需要预定义 tabbar 配置，请在任意位置使用 useRouter, 并传入 tabBarList， 即可全局使用。


另，小程序下的 `URL is not a constructor` 错误已修复： 147052dddb2c137fb5af550647a6d00f31306034
